AWSTemplateFormatVersion: 2010-09-09
Description: Plantilla Base para Ibexcm
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Stack Environment
      Parameters:
      - EnvTag
      - TipoAmbiente
      - AmbienteDBseparado
    - Label:
        default: Network Configuration
      Parameters:
      - VPCcidr
      - AvailabilityZoneA
      - AvailabilityZoneB
      - SubnetPublicAcidr
      - SubnetPublicBcidr
      - SubnetPrivateAcidr
      - SubnetPrivateBcidr
      - SubnetDBPrivateAcidr
      - SubnetDBPrivateBcidr
    ParameterLabels:
      EnvTag:
        default: Valor para tag Env
      TipoAmbiente:
        default: Seleccione el Tipo de Ambiente
      AmbienteDBseparado:
        default: Indique SI para Arquitectura de 3 capas o NO para Arquitectura de
          2 capas
      VPCcidr:
        default: Define CIDR for VPC
      SubnetPublicAcidr:
        default: Define CIDR for Public Subnet A
      SubnetPublicBcidr:
        default: Define CIDR for Public Subnet B
      SubnetPrivateAcidr:
        default: Define CIDR for Private Subnet A
      SubnetPrivateBcidr:
        default: Define CIDR for Private Subnet B
      SubnetDBPrivateAcidr:
        default: Define CIDR for DB Private Subnet A
      SubnetDBPrivateBcidr:
        default: Define CIDR for DB Private Subnet B
      AvailabilityZoneA:
        default: Availability zone for resources in side A
      AvailabilityZoneB:
        default: Availability zone for resources in side B
Parameters:
  TipoAmbiente:
    Type: String
    Description: 'Tipo de Ambiente para VPC: PROD, TEST'
    Default: TEST
    AllowedValues:
    - PROD
    - TEST
    ConstraintDescription: 'Por favor indique el tipo de ambiente: PROD o TEST'
  AmbienteDBseparado:
    Type: String
    Description: Arquitectura de 3 capas contempla subnet privada adicional para DB
    Default: 'NO'
    AllowedValues:
    - SI
    - 'NO'
    ConstraintDescription: Por favor indique SI o NO
  VPCcidr:
    Type: String
    Description: Rango CIDR para VPC
    Default: 192.168.0.0/16
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block usa la sintaxis x.x.x.x/16-28
  SubnetPublicAcidr:
    Type: String
    Description: Rango CIDR para Subnet Publica A
    Default: 192.168.10.0/24
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block usa la sintaxis x.x.x.x/16-28
  SubnetPublicBcidr:
    Type: String
    Description: Rango CIDR para Subnet Publica B
    Default: 192.168.30.0/24
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block usa la sintaxis x.x.x.x/16-28
  SubnetPrivateAcidr:
    Type: String
    Description: Rango CIDR para Subnet Privada A
    Default: 192.168.20.0/24
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block usa la sintaxis x.x.x.x/16-28
  SubnetPrivateBcidr:
    Type: String
    Description: Rango CIDR para Subnet Privada B
    Default: 192.168.40.0/24
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block usa la sintaxis x.x.x.x/16-28
  SubnetDBPrivateAcidr:
    Type: String
    Description: Rango CIDR para Subnet DB Privada A
    Default: 192.168.55.0/24
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block usa la sintaxis x.x.x.x/16-28
  SubnetDBPrivateBcidr:
    Type: String
    Description: Rango CIDR para Subnet DB Privada B
    Default: 192.168.65.0/24
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block usa la sintaxis x.x.x.x/16-28
  EnvTag:
    Type: String
    Description: Tag de Ambiente para los Recursos
    Default: test
  AvailabilityZoneA:
    Type: AWS::EC2::AvailabilityZone::Name
    Description: AZ para lado A
  AvailabilityZoneB:
    Type: AWS::EC2::AvailabilityZone::Name
    Description: AZ para lado B
  Keyparam:
    Type: AWS::EC2::KeyPair::KeyName
    Description: KeyPair para EC2
  CertificadoARN:
    Type: String
    Description: ARN del certificado para ALB Front
  KMSKeyARN:
    Type: String
    Description: ARN de llave de KMS
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/ibexcm-templates/a678eadb403e336a4eaea45e6f84d5c6.template
      Parameters:
        TipoAmbiente:
          Ref: TipoAmbiente
        AmbienteDBseparado:
          Ref: AmbienteDBseparado
        VPCcidr:
          Ref: VPCcidr
        SubnetPublicAcidr:
          Ref: SubnetPublicAcidr
        SubnetPublicBcidr:
          Ref: SubnetPublicBcidr
        SubnetPrivateAcidr:
          Ref: SubnetPrivateAcidr
        SubnetPrivateBcidr:
          Ref: SubnetPrivateBcidr
        SubnetDBPrivateAcidr:
          Ref: SubnetDBPrivateAcidr
        SubnetDBPrivateBcidr:
          Ref: SubnetDBPrivateBcidr
        EnvTag:
          Ref: EnvTag
        AvailabilityZoneA:
          Ref: AvailabilityZoneA
        AvailabilityZoneB:
          Ref: AvailabilityZoneB
  SGStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/ibexcm-templates/0ae4405755befe94be2d13764b0298c7.template
      Parameters:
        EnvTag:
          Ref: EnvTag
        VPCID:
          Fn::GetAtt:
          - VPCStack
          - Outputs.VPCID
  ComputeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/ibexcm-templates/269bd1c6f50fea69e52c6c530cf69467.template
      Parameters:
        EnvTag:
          Ref: EnvTag
        Keyparam:
          Ref: Keyparam
        CertificadoARN:
          Ref: CertificadoARN
        VPCID:
          Fn::GetAtt:
          - VPCStack
          - Outputs.VPCID
        subnetPublicA:
          Fn::GetAtt:
          - VPCStack
          - Outputs.subnetPublicA
        subnetPublicB:
          Fn::GetAtt:
          - VPCStack
          - Outputs.subnetPublicB
        subnetPrivateA:
          Fn::GetAtt:
          - VPCStack
          - Outputs.subnetPrivateA
        subnetPrivateB:
          Fn::GetAtt:
          - VPCStack
          - Outputs.subnetPrivateB
        bastionLinuxSg:
          Fn::GetAtt:
          - SGStack
          - Outputs.bastionLinuxSg
        albFrontSg:
          Fn::GetAtt:
          - SGStack
          - Outputs.albFrontSg
        albPrivSg:
          Fn::GetAtt:
          - SGStack
          - Outputs.albPrivSg
  ClientsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/ibexcm-templates/9d70e295c9428f4f722d5528ec60e98d.template
      Parameters:
        EnvTag:
          Ref: EnvTag
        CertificadoARN:
          Ref: CertificadoARN
        KMSKeyARN:
          Ref: KMSKeyARN
