version: 0.2

phases:
  install:
    commands:
      - wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
      - mv jq-linux64 jq
      - chmod +x jq
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - REPOSITORY_URI=$(echo $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-9)
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo $COMMIT_HASH
      - echo "Setting Build Variables"
      - ADMIN_ACCOUNT_EMAIL_ADDRESS=$(echo $SECRET | ./jq -r '.ADMIN_ACCOUNT_EMAIL_ADDRESS')
      - IP_ADDRESS=$(echo $SECRET | ./jq -r '.IP_ADDRESS')
      - URL_PROTOCOL=$(echo $SECRET | ./jq -r '.URL_PROTOCOL')
      - EMAIL_FROM=$(echo $SECRET | ./jq -r '.EMAIL_FROM')
      - SENDGRID_API_KEY=$(echo $SECRET | ./jq -r '.SENDGRID_API_KEY')
      - SENDGRID_API_URL=$(echo $SECRET | ./jq -r '.SENDGRID_API_URL')
      - SENDGRID_TEMPLATE_HOST=$(echo $SECRET | ./jq -r '.SENDGRID_TEMPLATE_HOST')
      - TWILIO_SID=$(echo $SECRET | ./jq -r '.TWILIO_SID')
      - TWILIO_AID=$(echo $SECRET | ./jq -r '.TWILIO_AID')
      - TWILIO_TOKEN=$(echo $SECRET | ./jq -r '.TWILIO_TOKEN')
      - JWT_PUBLIC_KEY=$(echo $SECRET | ./jq -r '.JWT_PUBLIC_KEY')
      - JWT_PRIVATE_KEY=$(echo $SECRET | ./jq -r '.JWT_PRIVATE_KEY')
      - GRAPHQL_PORT=$(echo $SECRET | ./jq -r '.GRAPHQL_PORT')
      - GRAPHQL_ENDPOINT=$(echo $SECRET | ./jq -r '.GRAPHQL_ENDPOINT')    
      - SHIFTM_USERNAME=$(echo $SECRET | ./jq -r '.SHIFTM_USERNAME')
      - SHIFTM_PASSWORD=$(echo $SECRET | ./jq -r '.SHIFTM_PASSWORD')
      - SHIFTM_EXCHANGE_NAME=$(echo $SECRET | ./jq -r '.SHIFTM_EXCHANGE_NAME')
      - PRISMA_SECRET=$(echo $SECRET | ./jq -r '.PRISMA_SECRET')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build
        --build-arg ADMIN_ACCOUNT_EMAIL_ADDRESS=$ADMIN_ACCOUNT_EMAIL_ADDRESS
        --build-arg IP_ADDRESS=$IP_ADDRESS
        --build-arg URL_PROTOCOL=$URL_PROTOCOL
        --build-arg EMAIL_FROM=$EMAIL_FROM
        --build-arg SENDGRID_API_KEY=$SENDGRID_API_KEY
        --build-arg SENDGRID_API_URL=$SENDGRID_API_URL
        --build-arg SENDGRID_TEMPLATE_HOST=$SENDGRID_TEMPLATE_HOST
        --build-arg TWILIO_SID=$TWILIO_SID
        --build-arg TWILIO_AID=$TWILIO_AID
        --build-arg TWILIO_TOKEN=$TWILIO_TOKEN
        --build-arg JWT_PRIVATE_KEY=$JWT_PRIVATE_KEY
        --build-arg JWT_PUBLIC_KEY=$JWT_PUBLIC_KEY
        --build-arg GRAPHQL_PORT=$GRAPHQL_PORT
        --build-arg GRAPHQL_ENDPOINT=$GRAPHQL_ENDPOINT
        --build-arg PRISMA_ENDPOINT=$PRISMA_ENDPOINT
        --build-arg PRISMA_SECRET=$PRISMA_SECRET
        --build-arg SHIFTM_USERNAME=$SHIFTM_USERNAME
        --build-arg SHIFTM_PASSWORD=$SHIFTM_PASSWORD
        --build-arg SHIFTM_EXCHANGE_NAME=$SHIFTM_EXCHANGE_NAME
        -t $REPOSITORY_URI:$IMAGE_TAG-latest
        -f graphqlserver/Dockerfile .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG-latest $REPOSITORY_URI:$IMAGE_TAG-$COMMIT_HASH
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG-latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG-$COMMIT_HASH
